sudo: required
dist: trusty
env:
  global:
    - secure: j64L+YB6ZTOwP7joFBfSAMv6scssInUw91BgJqc/dRLU6nd4d2n8as4qYGbGPZ09nIYES+baD7W73WVr0Hljvnis2wKA36BcuzyLlcGugUtuDigVG/X5RDWs4EYh5URSOFO5j+I+2QKFWnYKydiQbnimBdTr3SEI9QBGFoywNVRUPaOquuyQwk3dYb7s4Fc8NHkNJF9xJ/dq+GrFIBmXHDuq7d+J2Ex2rZ5LADBiResASnMLSUNLtrtzOlMi5GE7cT6xKpnNigc2EpKmhQxrWG1/P9x+KgIQvMG+7fbYzmr076Hvl5DGvRW1JDW69fbXOTCZtXBjveDV79JFd9+KJnYbBaMD262ZJJ+zFwhUu+faKOZqejeO10VRJONda4q3RBfcFF21nZmFbuI3t/pJWJpXX8+r1/5/OkMhvuZf6HNIQhrk2kKEUx6yaPW5xjKQLCrFkEASgImRFDzKtr1XFmh3fJAGsU/WDbtgs8hZy8YiiHHtUYckTG8RjZTLulO8VM277L1tWubNKYDUEhfg+c5bovl/XomttnGuXm5Z0Cve9ZOBc6leOPwi4FP5WsAXpD9AxJDOE1215OxZRX0LxKOAHVfPLfjSLABPeCc6JnfoE1c5HWVQg7OAfMveleDdNaOemkDp3O5klOsOmD2w4E7CZUc2IBz2FbsZQ2ML61U=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/Badd-Boyz-Hosts
    - GIT_BRANCH: master
  matrix:
    - USE_NETWORK=true
php:
  - '5.6'
cache:
  - apt
addons:
  apt:
    packages:
      - realpath

before_install:
  - export TZ=Africa/Johannesburg
  - sudo apt-get -y install expect
  - sudo apt-get -y install whois
  - sudo apt-get -y install dos2unix

script:
  - bash .dev-tools/generate-hosts.sh
  #- bash .dev-tools/run-funceble.sh
  - bash .dev-tools/modify-files-and-commit.sh
  #- travisCI/ping-test.sh

before_deploy:
  - .dev-tools/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - "hosts"
  skip_cleanup: true
  on:
    repo: mitchellkrogza/Badd-Boyz-Hosts
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  email: false