language: php
sudo: required
dist: trusty
env:
  global:
    - secure: j64L+YB6ZTOwP7joFBfSAMv6scssInUw91BgJqc/dRLU6nd4d2n8as4qYGbGPZ09nIYES+baD7W73WVr0Hljvnis2wKA36BcuzyLlcGugUtuDigVG/X5RDWs4EYh5URSOFO5j+I+2QKFWnYKydiQbnimBdTr3SEI9QBGFoywNVRUPaOquuyQwk3dYb7s4Fc8NHkNJF9xJ/dq+GrFIBmXHDuq7d+J2Ex2rZ5LADBiResASnMLSUNLtrtzOlMi5GE7cT6xKpnNigc2EpKmhQxrWG1/P9x+KgIQvMG+7fbYzmr076Hvl5DGvRW1JDW69fbXOTCZtXBjveDV79JFd9+KJnYbBaMD262ZJJ+zFwhUu+faKOZqejeO10VRJONda4q3RBfcFF21nZmFbuI3t/pJWJpXX8+r1/5/OkMhvuZf6HNIQhrk2kKEUx6yaPW5xjKQLCrFkEASgImRFDzKtr1XFmh3fJAGsU/WDbtgs8hZy8YiiHHtUYckTG8RjZTLulO8VM277L1tWubNKYDUEhfg+c5bovl/XomttnGuXm5Z0Cve9ZOBc6leOPwi4FP5WsAXpD9AxJDOE1215OxZRX0LxKOAHVfPLfjSLABPeCc6JnfoE1c5HWVQg7OAfMveleDdNaOemkDp3O5klOsOmD2w4E7CZUc2IBz2FbsZQ2ML61U=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: builds@travis-ci.org
    - TRAVIS_REPO_SLUG: mitchellkrogza/Badd-Boyz-Hosts
    - GIT_BRANCH: master
matrix:
  fast_finish: true
php:
  - '5.6'
cache:
  - apt
addons:
  apt:
    packages:
      - realpath
script:
  #- cd /etc
  - sudo wget https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts.deny
  - sudo mv /home/travis/build/mitchellkrogza/Badd-Boyz-Hosts/hosts.deny.1 /etc/hosts.deny
  #- cat /etc/hosts.deny &> /dev/stdout
  - ifconfig -a &> /dev/stdout
  - sudo service network-manager restart
  #- sudo find / -name "hosts" &> /dev/stdout
  #- ls -la /home/travis/build/mitchellkrogza/ &> /dev/stdout
  - ping -c 4 freelotto.com &> /dev/stdout
  #- cat /tmp/error.log
#before_deploy:
#  - travisCI/deploy.sh
#deploy:
#  provider: releases
#  api_key:
#    secure: ${GH_TOKEN}
#  file:
#  - "conf.d/globalblacklist.conf"
#  skip_cleanup: true
#  on:
#    repo: mitchellkrogza/nginx-ultimate-bad-bot-blocker
#    tags: false
#    all_branches: true
#notifications:
#    email: false